### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SamJBarney** [sfider/coroutine#1]
I know this repository is over two years old, but I was wondering if you had ever run into problems with the ret opcode throwing a EXC_BAD_INSTRUCTION (code=12, subcode=0x0) before. Have you?
I'm trying to base a scheduling runtime off of your code for fun.

**Comment by sfider** [comment]
Sorry, but I won't be of any help. Too much time have past and I don't remember problems I had when I worked on this. Nonetheless, I wish you luck solving this ;)
